### ISSUE TITLE
code explanation

### ISSUE THREAD

**Issue by rchicoli** [fteychene/logspout-logstash#1]
Hey @fteychene

I've been learning golang since past months and came up with some exclamation marks after looking at your code changes.
I would be grateful if you could explain me how this works, because I was planning to rewrite it an publish to the main repository.

It is still confusing for me when using pointers and references. How does the assertion works on following function?

``` golang
func runCollapseChannel(channel chan LogstashMessage, sendMessage func(message LogstashMessage)) {
    var collapse *LogstashMessage
.
.
        case collapse != nil && log.Type == (*collapse).Type:
```

Thanks in advanced

**Comment by rchicoli** [comment]
nvm I will close this and try to learn by my self.

**Comment by fteychene** [comment]
Hi
I just read your message. I look at my code and I will reply to you.

**Comment by fteychene** [comment]
For this assertion,  the purpose is to validate that a previous message exists `collapse != nil` and that the property type of the pointed value is equals to log.Type.

The first assertion is just to avoid error on the real check if the pointer doesn't reference any value.

**Comment by rchicoli** [comment]
hey @fteychene thx a lot, it helps me a bit to understand. Tonight I will do couple of tests to try to clarify the rest.
